Code refactoring, including changing filters to jinja tests
tutorcruncher/django-jinja-bootstrap-form pull request #3
Opened 2017-07-24 10:42 UTC by raphendyr

Iterated over the code...

Most important are the first two commits. First will allow jinja to use cached version of field_macros as the context is not exposed (there is no need to do that). Second makes the templates way more clear by using jinta test syntax instead of django like filters. In addition it doesn't pollute filter namespace with strange filters.

Last two commits rewrite render and bootstrap_horizontal.

In addition, I added some comments :smile:

2017-07-24 11:08 UTC, samuelcolvin commented
tests seem to be failing.

2017-07-24 11:22 UTC, samuelcolvin requested changes
In general I think this looks good, but there needs to be a bit of work done before it's ready to merge.

We've been using django-jinja-bootstrap-form in production a lot for years and it's "just worked" so we need to make absolutely sure it's functionality hasn't altered before releasing an update.

If you get tests passing and fix the majority of the commends, I'll merge then improve tests, coverage, linting etc.

2017-07-24 11:22 UTC, samuelcolvin commented on bootstrapform_jinja/templatetags/bootstrap.py
> +from django.forms import CheckboxInput, CheckboxSelectMultiple, \
I don't think we document it here, but we always use 120 max line length and parenthesis when imports span multiple lines/

2017-07-24 11:22 UTC, samuelcolvin commented on bootstrapform_jinja/templatetags/bootstrap.py
> +from django.utils.six import string_types
I have a policy that all code written or edited since 1st Jan 2017 is python 3.5+ only. Is that ok with you?

2017-07-24 11:22 UTC, samuelcolvin commented on bootstrapform_jinja/templatetags/bootstrap.py
> +        return ' '.join((str(x) for x in self))
no need for extra parenthesis `return ' '.join(str(x) for x in self)`

2017-07-24 11:22 UTC, samuelcolvin commented on bootstrapform_jinja/templatetags/bootstrap.py
> +        return ' '.join((str(x) for x in self))
or even just `' '.join(map(str, self))`

2017-07-24 11:22 UTC, samuelcolvin commented on bootstrapform_jinja/templatetags/bootstrap.py
> +class ClassSet(set):
`SpaceSet` would be a more sensible name I think.

2017-07-24 11:22 UTC, samuelcolvin commented on bootstrapform_jinja/templatetags/bootstrap.py
> +    for cl in label_cols:
don't think I wrote this originally, it came from django bootstrap form. I'll believe you that it works if we have some proper tests and coverage.

2017-07-24 15:02 UTC, raphendyr commented on bootstrapform_jinja/templatetags/bootstrap.py
> +from django.utils.six import string_types
It's. Did that only as I wasn't sure and it wasn't too complicated.

2017-07-24 15:03 UTC, raphendyr commented on bootstrapform_jinja/templatetags/bootstrap.py
> +from django.forms import CheckboxInput, CheckboxSelectMultiple, \
I prefer parenthesis my self too, but used that format for some reason. I'll check the 120 limit too.

2017-07-24 15:04 UTC, raphendyr commented on bootstrapform_jinja/templatetags/bootstrap.py
> +class ClassSet(set):
Probably. Less s letters at least :)

2017-07-24 15:06 UTC, raphendyr commented on bootstrapform_jinja/templatetags/bootstrap.py
> +        return ' '.join((str(x) for x in self))
If I remember right python 2.7 required extra parenthesis, but as that doesn't need to be supported those could be dropped for sure. Note to self: remember that map function exists...

2017-07-24 15:08 UTC, raphendyr commented on bootstrapform_jinja/templatetags/bootstrap.py
> +    for cl in label_cols:
Yeah. It clearly was just copy from the original source. Though, I didn't have interest of rewriting that. In perfect world both codes would use same implementation. I'm most afraid that I made some mistake when doing this part.

2017-07-24 15:48 UTC, raphendyr commented
I fixed the test framework and only difference in horizontal is different order of classes (due to set) as assertHTMLEqual doesn't compare them. So `' '.join(sorted(map(str, self)))` would probably be good?

2017-07-24 16:13 UTC, samuelcolvin commented
> I was planning of using ' '.join(sorted(map(str, self))) to sort this out.

LGTM

2017-07-26 04:20 UTC, raphendyr commented
Removed usage of the set and just made sure the input doesn't contain duplicates (and is strings, which would have broken the for loop any case). The code should be bit more clear now.

I changed the tests a bit to work in django 1.9 and up (version test didn't work correctly). I also replace render_to_response with render (as previous is deprecated). Only change in the template output is spaces in class attributes, so nothing in functionality should have changed.

2017-07-26 05:48 UTC, raphendyr commented
Tests where failing in travis as with django 1.8 and 1.7 django-jinja wasn't importing templatetags for some reason. Now AppConfig file will do it in the ready method (supported in django 1.7). I also fixed tests up to django 1.11 and added those to travis.

2017-07-26 19:07 UTC, samuelcolvin commented
Look good initially, I'll have a proper look tomorrow.

By the way before the next release I'll drop support for python <3.5 and django <1.8 and anything before the latest django-jinja. Hope that's ok with you.

2017-07-27 11:51 UTC, raphendyr commented
Should be fine.

2017-07-28 16:48 UTC, samuelcolvin approved these changes

2017-07-28 16:48 UTC, tomhamiltonstubber approved these changes

2017-07-28 16:48 UTC, samuelcolvin commented
thanks a lot.

2017-07-28 16:48 UTC, merged